#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 231
  unit_system: imperial
  time_zone: America/Chicago
  
#################################################################
## Customize
#################################################################
  
  customize:
     binary_sensor.floorplan:
       custom_ui_state_card: floorplan
       config: !include floorplan.yaml
     sensor.weather_humidity:
       icon: mdi:water-percent
     sensor.weather_precip_probability:
       icon: mdi:weather-rainy
     light.den_lights_level:
       friendly_name: Den lights
     light.linear_wd500z1_wall_dimmer_switch_level:
       friendly_name: Kitchen lights
     sensor.dark_sky_temperature:
       friendly_name: Temperature
     sensor.dark_sky_summary:
       friendly_name: Summary
     sensor.dark_sky_precip_probability:
       friendly_name: Precipitation
     sensor.dark_sky_humidity:
       friendly_name: Humidity
     sensor.dark_sky_pressure:
       friendly_name: Pressure
     sensor.thermostat_temperature:
       friendly_name: Temperature
     sensor.thermostat_humidity:
       friendly_name: Humidity
     sensor.everspring_st812_flood_detector_alarm_level:
       friendly_name: Sump Alarm Level
     sensor.everspring_st812_flood_detector_alarm_type:
       friendly_name: Sump Alarm Type
     sensor.everspring_st812_flood_detector_flood:
       friendly_name: Sump Alarm
     group.all_automations:
       hidden: false
     sensor.dark_sky_daily_high_temperature:
       friendly_name: High
     sensor.dark_sky_daily_high_apparent_temperature:
       friendly_name: Apparent high
     sensor.dark_sky_daily_low_temperature:
       friendly_name: Low
     sensor.dark_sky_hourly_summary:
       friendly_name: Summary

#################################################################
## General Configurations
#################################################################

updater:
sun:
config:
discovery:
frontend:
conversation:
logbook:
recorder:
  db_url: !secret mysql_login
history:
  exclude:
    domains:
      - light
      - automation
      - media_player
    entities:
      - group.all_lights
      - group.all_switches
      - group.downstairs_lights
      - group.family
      - group.network

#################################################################
## Floorplan
#################################################################

# Need a dummy sensor to make floorplan work

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
      
#################################################################
## HTTP(S) access
#################################################################

http:
    api_password: !secret http_password
    ssl_certificate: !secret ssl_cert
    ssl_key: !secret ssl_key
    base_url: !secret public_url
    trusted_networks:
      - 192.168.1.0/24
    ip_ban_enabled: True
    login_attempts_threshold: 3

#################################################################
## Lights
#################################################################

light:
  platform: hue
  host: 192.168.1.20
  allow_unreachable: true

#################################################################
## Theromstat
#################################################################   

ecobee:
  api_key: !secret ecobee_api_key
   
#################################################################
## Device tracking
#################################################################

device_tracker:
  - platform: ubus
    host: 192.168.1.1
    username: root
    password: !secret password
    consider_home: 180
    track_new_devices: false
  - platform: owntracks
  
#################################################################
## Alexa and Google Home
#################################################################

emulated_hue:
  host_ip: 192.168.1.25
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - light
    - switch
 
#################################################################
##  Media  players
#################################################################

media_player:
  - platform: samsungtv
    host: 192.168.1.131
    mac: BC:8C:CD:51:A9:FA
    name: Bedroom TV
 
#################################################################
## Text to speech
#################################################################

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#################################################################
## IFTTT
#################################################################

ifttt:
  key: !secret ifttt_key
  
#################################################################
## Enable Cloud MQTT broker
#################################################################

mqtt:
  broker: m12.cloudmqtt.com
  port: !secret mqtt_port
  client_id: hass
  keepalive: 60
  username: !secret mqtt_user
  password: !secret password

#################################################################
## Harmony hub
#################################################################

remote:
  - platform: harmony
    name: Den
    host: 192.168.1.198 

#################################################################
## Weather radar
#################################################################

camera:
  - platform: generic
    still_image_url: !secret radar_url
    name: Radar

#################################################################
## Zwave
#################################################################

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/src/python-openzwave/openzwave/config
  device_config:
    light.linear_wd500z1_wall_dimmer_switch_level:
      polling_intensity: 1


#################################################################
## Includes
#################################################################

automation: !include automations.yaml
group: !include group.yaml
notify: !include notify.yaml
scene: !include scene.yaml
script: !include_dir_named scripts
sensor: !include sensor.yaml
shell_command: !include shell.yaml
zone: !include zones.yaml
